### ISSUE TITLE
Support "Emit fields with default values"

### ISSUE THREAD

**Issue by rty813** [google/protobuf.dart#735] opened 2022-08-19 10:21 UTC
[JSON options](https://developers.google.com/protocol-buffers/docs/proto3#json_options)

> A proto3 JSON implementation may provide the following options:
     Emit fields with default values: Fields with default values are omitted by default in proto3 JSON output. An implementation 
 may provide an option to override this behavior and output fields with their default values.

Given, for example, the following proto definitions:
```
message X{
  int n = 1;
}
```

my code:
```
x = X();
print(x.toProto3Json());
```

Current output: `{}`
What I want: `{n: 0}`

**Comment by osa1** [comment] 2022-08-22 07:47
Duplicate of #585 (PR #592).

**Closed by osa1** 2022-08-22 07:47 UTC
