### ISSUE TITLE
Proto2 and proto3 cannot be mixed up, or the model cannot be transformed

### ISSUE THREAD

**Issue by bravekingzhang** [google/protobuf.dart#361] opened 2020-03-15 09:48 UTC

**Comment by sigurdm** [comment] 2020-03-16 09:39
Not sure I understand the issue.
Can you give an example of what doesn't work?

**Comment by osa1** [comment] 2022-04-13 12:35
It's unclear what the problem is and the author has been unresponsive. Closing.

**Closed by osa1** 2022-04-13 12:35 UTC
