### ISSUE TITLE
protoc_plugin should depend on newer dart_style

### ISSUE THREAD

**Issue by Gursewak-Uppal** [google/protobuf.dart#567] opened 2022-01-03 11:45 UTC
Running "flutter pub get" in MyProject...

```
Because no versions of protoc_plugin match >20.0.0 <21.0.0 and protoc_plugin 20.0.0 depends on dart_style ^1.0.6, protoc_plugin ^20.0.0 requires dart_style ^1.0.6.
And because source_gen >=1.0.0 depends on dart_style ^2.0.0, protoc_plugin ^20.0.0 is incompatible with source_gen >=1.0.0.
So, because MyProject depends on both source_gen 1.2.1 and protoc_plugin ^20.0.0, version solving failed.
pub get failed (1; So, because MyProject depends on both source_gen 1.2.1 and protoc_plugin ^20.0.0, version solving failed.)
```

Process finished with exit code 1

**Comment by siloebb** [comment] 2022-01-07 20:44
I think that the version in Pub is wrong? Let me test using override

**Comment by siloebb** [comment] 2022-01-07 20:49
Using dependency override with I can use the pub get.
So I really think that there is an error in version published in the Pub


```
dependency_overrides:
  protoc_plugin:
    git:
      url: git@github.com:google/protobuf.dart.git
      path: protoc_plugin
```

**Comment by sigurdm** [comment] 2022-01-10 09:09
If you read the message from pub you see there is a conflict. protoc_plugin relies on an older dart_style, incompatible with the one from source_gen.

We should up the bound.

**Comment by osa1** [comment] 2022-03-23 12:07
`dart_style` dependency was bumped in 8571b58e, but it seems like we haven't published a release with that commit yet. Latest on dart.pub still uses `^1.0.6`: https://pub.dev/packages/protoc_plugin/pubspec

**Comment by osa1** [comment] 2022-04-11 13:08
Closing as duplicate of #537.

**Closed by osa1** 2022-04-11 13:08 UTC
