### ISSUE TITLE
[Bug][proto3] inconsistent behavior of assigning null value for optional string

### ISSUE THREAD

**Issue by thanhdatvo** [google/protobuf.dart#794] opened 2023-01-26 23:20 UTC
```proto
syntax = "proto3";

package test;

message SomeMessage { optional string optional_string = 1; }
```
When I use this message in dart code like this:
```dart
final someMessage = SomeMessage(optionalString: null);
someMessage.optionalString = null; // error
```
It throwed an error: 
"
A value of type 'Null' can't be assigned to a variable of type 'String'.
Try changing the type of the variable, or casting the right-hand type to 'String'
"
I think it should be consistent between initialization and reassign value for message attributes.

**Comment by osa1** [comment] 2023-01-31 09:20
Duplicate of #523, #493, and many others. #790 is fixing this.

**Closed by osa1** 2023-01-31 09:20 UTC
