### ISSUE TITLE
Support for generating Comment

### ISSUE THREAD

**Issue by EpicKim** [google/protobuf.dart#365] opened 2020-04-14 06:48 UTC
i have a test file like this:

```proto
syntax = "proto2";

message Test {
  // tag
  required string label = 1;
  required int64 reps = 3; // reps
}
```

run `protoc --dart_out=./output test.proto` to generate code.

And i found that in generated file property don't have comment.

As in below

```dart
///
//  Generated code. Do not modify.
//  source: test.proto
//
// @dart = 2.3
// ignore_for_file: camel_case_types,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type

import 'dart:core' as $core;

import 'package:fixnum/fixnum.dart' as $fixnum;
import 'package:protobuf/protobuf.dart' as $pb;

class Test extends $pb.GeneratedMessage {
  static final $pb.BuilderInfo _i = $pb.BuilderInfo('Test', createEmptyInstance: create)
    ..aQS(1, 'label')
    ..a<$fixnum.Int64>(3, 'reps', $pb.PbFieldType.Q6, defaultOrMaker: $fixnum.Int64.ZERO)
  ;

  Test._() : super();
  factory Test() => create();
  factory Test.fromBuffer($core.List<$core.int> i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromBuffer(i, r);
  factory Test.fromJson($core.String i, [$pb.ExtensionRegistry r = $pb.ExtensionRegistry.EMPTY]) => create()..mergeFromJson(i, r);
  Test clone() => Test()..mergeFromMessage(this);
  Test copyWith(void Function(Test) updates) => super.copyWith((message) => updates(message as Test));
  $pb.BuilderInfo get info_ => _i;
  @$core.pragma('dart2js:noInline')
  static Test create() => Test._();
  Test createEmptyInstance() => create();
  static $pb.PbList<Test> createRepeated() => $pb.PbList<Test>();
  @$core.pragma('dart2js:noInline')
  static Test getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<Test>(create);
  static Test _defaultInstance;

  @$pb.TagNumber(1)
  $core.String get label => $_getSZ(0);
  @$pb.TagNumber(1)
  set label($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasLabel() => $_has(0);
  @$pb.TagNumber(1)
  void clearLabel() => clearField(1);

  @$pb.TagNumber(3)
  $fixnum.Int64 get reps => $_getI64(1);
  @$pb.TagNumber(3)
  set reps($fixnum.Int64 v) { $_setInt64(1, v); }
  @$pb.TagNumber(3)
  $core.bool hasReps() => $_has(1);
  @$pb.TagNumber(3)
  void clearReps() => clearField(3);
}
```

**Comment by Jonas-Sander** [comment] 2020-11-13 22:41
I tried to generate `googleapis` but it is really unmanagable to use if there are no comments.

**Comment by upday7** [comment] 2020-11-25 16:16
it is appreciated to have this feature so that we can get rid of to check comments in proto files .. 

pls keep updated the progress, thanks.

**Comment by MattyBoy4444** [comment] 2021-09-21 10:11
Please add this feature.  c# has had this for a while.

**Comment by osa1** [comment] 2022-04-14 07:02
Duplicate of #161.

**Closed by osa1** 2022-04-14 07:02 UTC
