### ISSUE TITLE
`protoc` does not generate built-in types

### ISSUE THREAD

**Issue by khteh** [google/protobuf.dart#910] opened 2024-01-30 06:46 UTC
`/proto/ping.proto`:
```
syntax = "proto3";
import "google/protobuf/empty.proto";
service SvcPing {
  rpc Ping (google.protobuf.Empty) returns (Pong);
}

message Pong {
  string message = 1;
}
```
Running the command `protoc proto/ping.proto --dart_out=grpc:lib/grpc` generates the necessary code but without the `"google/protobuf/empty.proto"`:
![image](https://github.com/google/protobuf.dart/assets/3871483/cc1453de-7c9b-426b-abe6-751090051a5c)

**Comment by osa1** [comment] 2024-02-28 07:57
Duplicate of #780.

**Closed by osa1** 2024-02-28 07:57 UTC
